### ISSUE TITLE
Invisable "Wall" when minecraft is in 854x480 and dragging mods

### ISSUE THREAD

**Issue by egold555** [egold555/Minecraft-1.8.8-PVP-Client-Series#2]
"hey Eric
any idea how to fix this
https://gyazo.com/e28f463c334809ffad1b53d4f429dca6
it's like there's an invisible box there and the mod doesn't move
other users say they have this issue too

it only happens when the game is in that small mode
not when its full screen windowd"

**Comment by egold555** [comment]
Does this relate to #4 need to test

**Comment by ghost** [comment]
~As for this whatever method you use to check if your mouse is inside a box is wrong.~
~The correct method would be:~

~public boolean isInside (int mouseX, int mouseY, double x, double y, double x2, double y2)~
~{~
        ~return mouseX > x && mouseX < x2 && mouseY > y && mouseY < y2;~
        
~}~

~(I did not really look at your ClickGUI code or whatever, so I do not exactly know how)~
NVM something else is wrong, I believe that your isInside code or whatever and where you draw the dragging mods' x1,y1,x2,y2 may be different
