### ISSUE TITLE
Screen resolution is reported wrong from LWJGL

### ISSUE THREAD

**Issue by egold555** [egold555/Minecraft-1.8.8-PVP-Client-Series#3]
Seems to cause errors with resizing and mod positioning

LWJGL is reporting the wrong screen size. IDFK why in the world it is doing that

**Comment by egold555** [comment]
Seems to be fixed by making a new MCP project. I don't get it at this point

**Comment by ghost** [comment]
Hello!
Are you using Display.getWidth() and Display.getHeight()?
I do not recommend using that because MC has gui scale which changes their width and height value, however it does not change the lwjgl Display.getWidth() and Display.getHeight() value.

**Comment by ghost** [comment]
Also sorry for replying 2 years after lol but the issue is still open for some reason
