### ISSUE TITLE
Game Crashing Over And Over

### ISSUE THREAD

**Issue by MostlyGhostlyGaming** [egold555/Minecraft-1.8.8-PVP-Client-Series#7]
When trying to make the discord integrations, when i ran the code, it would crash before the game ever loaded. it keeps telling me there is a issue on line 10 in the Client.java file but no one knows what is wrong. Please help i have no idea what is happening

here is a crash log
[crash-2021-01-24_05.23.18-client.txt](https://github.com/egold555/Minecraft-1.8.8-PVP-Client-Series/files/5862387/crash-2021-01-24_05.23.18-client.txt)

**Comment by egold555** [comment]
Hi. Closing this issue. 

Please join the Discord support server for questions regarding the Client Series: [https://discord.gg/M3PAyyy](https://discord.gg/M3PAyyy)

**Comment by ghost** [comment]
Hello!
Have you put the library properly?
It looks like a library issue.
