### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by NoCPS** [egold555/Minecraft-1.8.8-PVP-Client-Series#9]
Can others see the cosmetics? If not can we render them somehow?

**Comment by NoCPS** [comment]
I'm new to java ...

**Comment by ben-l909** [comment]
nope

**Comment by egold555** [comment]
> Can others see the cosmetics? If not can we render them somehow?

It depends how it is implemented. If there is a server that manages the cosmetics then you can make it so other players can see cosmetics
